# Generated by Django 2.2 on 2019-05-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('answer_1', models.IntegerField(default=0)),
                ('answer_2', models.IntegerField(default=0)),
                ('answer_3', models.IntegerField(default=0)),
                ('answer_4', models.IntegerField(default=0)),
                ('answer_5', models.IntegerField(default=0)),
                ('answer_6', models.IntegerField(default=0)),
                ('answer_7', models.IntegerField(default=0)),
            ],
        ),
    ]
