# Generated by Django 2.2 on 2019-05-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
